# Copyright 2026 Harsha Krishne Gowda
# SPDX-License-Identifier: Apache-2.0

"""add key_sha256 index for fast auth lookup

Revision ID: c5e2a6c2703f
Revises: 38ef68bc6659
Create Date: 2026-03-19 09:03:09.765946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e2a6c2703f'
down_revision: Union[str, Sequence[str], None] = '38ef68bc6659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_api_keys_key_sha256'), 'api_keys', ['key_sha256'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key_sha256'), table_name='api_keys')
    op.drop_column('api_keys', 'key_sha256')
    # ### end Alembic commands ###
